stages:
  - build
  - test
  - security
  - deploy

container_scanning:
  stage: security
  image:
    name: docker:stable
  services:
    - docker:stable-dind
  script:
    - docker pull debian:bookworm-20211201
    - trivy image debian:bookworm-20211201
  artifacts:
    reports:
      container_scanning: gl-container-scanning-report.json
  tags:
    - macos
