stages:
  - check

# Джоба для проверки в папке all/all
check_all:
  stage: check
  image: python:3.9
  script:
    - echo "Checking for disallowed characters in all/all..."
    - if grep -q '[}]' all/all/*.md; then echo "Disallowed characters found in all/all"; exit 1; else echo "No disallowed characters found in all/all"; fi

# Джоба для проверки в папке project/calculator_proj
check_calculator_proj:
  stage: check
  image: python:3.9
  script:
    - echo "Checking for disallowed characters in project/calculator_proj..."
    - if grep -q '[}]' project/calculator_proj/*.md; then echo "Disallowed characters found in project/calculator_proj"; exit 1; else echo "No disallowed characters found in project/calculator_proj"; fi

# Джоба для проверки символов в корневой папке проекта
check_root:
  stage: check
  image: python:3.9
  script:
    - echo "Checking for disallowed characters in root directory..."
    - if grep -q '[}]' *.md; then echo "Disallowed characters found in root directory"; exit 1; else echo "No disallowed characters found in root directory"; fi

