stages:
  - build
  - test
  - security
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_VERIFY: "1"
  DOCKER_CERT_PATH: "/certs/client"

container_scanning:
  stage: security
  image: docker:stable
  services:
    - docker:dind
  script:
    - echo "Checking Docker daemon"
    - curl --unix-socket /var/run/docker.sock http://localhost/_ping
    - docker info
    - docker pull debian:bookworm-20211201
    - trivy image debian:bookworm-20211201
  artifacts:
    reports:
      container_scanning: gl-container-scanning-report.json
  tags:
    - macos
