stages:
  - check

variables:
  # Указываем версию Python, если это необходимо
  PYTHON_VERSION: "3.9"

check_formatting:
  stage: check
  image: python:$PYTHON_VERSION
  script:
    - echo "Checking for disallowed characters in files..."
    - if grep -q '[}]' *.md; then echo "Disallowed characters found"; exit 1; else echo "No disallowed characters found"; fi
  
  # Успешно завершится, если не найдено запрещенных символов

