stages:
  - build
  - test
  - security
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"

container_scanning:
  stage: security
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker info
    - docker pull debian:bookworm-20211201
    - trivy image debian:bookworm-20211201
  artifacts:
    reports:
      container_scanning: gl-container-scanning-report.json
  tags:
    - macos

