stages:
  - security

variables:
  # Настройка аутентификации Docker
  DOCKER_AUTH_CONFIG: '{"auths":{"https://index.docker.io/v1/":{"username":"$DOCKER_USERNAME","password":"$DOCKER_PASSWORD"}}}'
  # Указываем Docker Daemon
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

container_scanning:
  stage: security
  image: docker:stable
  services:
    - docker:dind
  script:
    - echo "$DOCKER_AUTH_CONFIG" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker info
    - docker pull debian:bookworm-20211201
    - trivy image debian:bookworm-20211201
  artifacts:
    reports:
      container_scanning: gl-container-scanning-report.json
  tags:
    - macos
