version: '3.8'
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    user: jenkins
    ports:
      - 8080:8080
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - jenkins_net

networks:
  jenkins_net:

volumes:
  jenkins_home:
    driver: local
